//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_productName___RoutingLogic {}

protocol ___VARIABLE_productName___DataPassing {
    var dataStore: ___VARIABLE_productName___DataStore? { get }
}

final class ___VARIABLE_productName___Router: ___VARIABLE_productName___RoutingLogic, ___VARIABLE_productName___DataPassing {
    weak var viewController: ___VARIABLE_productName___ViewController?
    var dataStore: ___VARIABLE_productName___DataStore?
    
    init(viewController: ___VARIABLE_productName___ViewController?, dataStore: ___VARIABLE_productName___DataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
}
