//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_productName___BusinessLogic {}

protocol ___VARIABLE_productName___DataStore {}

final class ___VARIABLE_productName___Interactor: ___VARIABLE_productName___BusinessLogic, ___VARIABLE_productName___DataStore {
    var presenter: ___VARIABLE_productName___PresentationLogic?
    
    init(presenter: ___VARIABLE_productName___PresentationLogic?) {
        self.presenter = presenter
    }
}
